language: node_js
node_js: ['10']
os: linux

# Build Packages to verify dependencies
script:
  - npm run bootstrap

# Configure settings needed for Lerna to manage releases.
# Based on https://github.com/geut/lerna-travis-demo#a---fully-automatic
before_deploy:
  - git config --global user.email ${GIT_COMMITTER_EMAIL}
  - git config --global user.name stencila-ci
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" > /dev/null 2>&1
  - git checkout master
  - git checkout .
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  # Deploy a new version of NPM packages and create a Github releases
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: npx lerna publish --yes
